### PR TITLE
Extend header() method to returns value at specified index, not always first

### PR DESCRIPTION
**Pull request by pali**

### CODE REVIEW

**Comment by rjbs** [comment]
It this an improvement over just indexing the list?

```
~$ perl -MEmail::Simple -E '$e = Email::Simple->create(header => [ X => 123, X => 234, X => 345 ]); say(($e->header("X"))[1])'
234
~$ perl -MEmail::Simple -E '$e = Email::Simple->create(header => [ X => 123, X => 234, X => 345 ]); say(($e->header("X"))[-1])'
345
```

**Comment by pali** [comment]
Yes, instead of returning unwanted data, now header() directly accept index parameter.

In future for Email::MIME I'm planning to add method header_as_obj() with parameters:
```
sub header_as_obj {
  my ($self, $name, $index, $class) = @_;
  ...
}
```

For header_as_obj() will be needed index parameter to prevent creation of useless objects.
And it would be better to have similar API for accessing n-th header value for Email::Simple and Email::MIME (with header_as_obj).

**Comment by rjbs** [comment]
Thanks!  Applied and release in v2.212 (TRIAL)

**Comment by pali** [comment]
Hi! It looks like you closed and rejected this pull request instead of merge (or fast-forward).

**Comment by rjbs** [comment]
Sorry, this was merged, but due to an error in my local configuration it was only pushed to my non-github repo.  I've pushed it up here, too.  Also, I'll cut a non-trial release this week.

**Comment by pali** [comment]
Btw, if you push code to github before closing pull reuqest, then github mark pull request with blue label "merged" (and autoclose pull request!) instead read label "closed" (as this one). With this you does not have to close pull request manually and also can be used to verify that you pushed needed code to github.

**Pull request closed without merging**
